### ISSUE TITLE
doom link missing

### ISSUE THREAD

**Issue by mandar1jn** [seckujdivad/fx-CG50SNAKE#1]
Hello. I would like a link to the doom repository mentioned. Could you provide me with one?

**Comment by seckujdivad** [comment]
The repo contained some macros and tricks to get certain C++ features to work without the standard library.  I wouldn't recommend that you use them because they ended up being more trouble than they were worth and mainly got around bugs in PrizmSDK.

The code in the repository would crash the calculator with a translation lookaside buffer error (because it was out of memory) because of the very inefficient algorithms used. I won't be trying to fix this and there's no code of value in there, so I won't make it public.

If you want a (possibly) working port of doom, here it is:
https://www.cemetech.net/downloads/files/755/x755
There's no source and knowing the limitations of these calculators I doubt a playable port or even a recreation will ever exist.

If you're just looking for games to play then go here:
https://www.cemetech.net/downloads/browse/prizm/games/

I've written some simpler 3D rendering code if that's what you're interested in:
https://github.com/seckujdivad/fx-CG50FirstPerson
